export interface CreateEmployer {
    firstName: string;
    lastName: string;
    sex: 'male' | 'female' | 'other';
    dateOfBirth: string;
    placeOfBirth: string;
    nationality: string;
    taxNumber: string;
    job: string;
    documentType: string;
    documentNumber: string;
    documentIssuer: string;
    documentExpiration: string;
    email: string;
    phone: string;
    address: string;
    city: string;
    state: string;
    province: string;
    zipCode: string;
    preferredContact: 'email' | 'phone';
    employmentType: 'full-time' | 'part-time' | 'temporary';
    notes: string;
    status: 'active' | 'inactive' | 'terminated';
    image?: string | null;
    imageUrl?: string | null;
    workersCount: number;
    id?: number;
    company?: string;
  }
